### ISSUE TITLE
fullUserInfo方法显示未授权无法获取accessToken

### ISSUE THREAD

**Issue by usualheart** [QingQiz/AoxiangRobot#14]
控制台错误：
```
Traceback (most recent call last):
...
  File "...\AoxiangRobot\venv\lib\site-packages\QingQiz\netreq\aoxiang.py", line 239, in userInfo
    res = self.fullUserInfo
  File "...\AoxiangRobot\venv\lib\site-packages\QingQiz\netreq\aoxiang.py", line 213, in fullUserInfo
    assert res['status'] == 'OK', 'error on request, message: ' + res['message']
KeyError: 'status'
```
调试发现无法获取到accessToken
![image](https://user-images.githubusercontent.com/29247191/103185316-db19fc00-48f6-11eb-9835-cbcda9d1a2b1.png)

**Comment by QingQiz** [comment]
这个我还真没法复现。。。
按道理来说，到取 access token 的时候肯定已经登录成功了，这时候 access token 应该已经在 cookie 里了

这种情况要么是认证失败了我没判断到，要么是 session 过期了

你看看你网页登录翱翔门户以后的 cookies 里有没有 access token
