### ISSUE TITLE
疫情填报不能正常使用？

### ISSUE THREAD

**Issue by MrKelvinChen** [QingQiz/AoxiangRobot#17]
本来想根据该项目改一个每日自动填报的机器人

结果测试时发现好像json序列化上有点问题（猜测）

```bash
[kelvin@fedora AoxiangRobot]$ python aoxiangRobot -u [手动隐藏] -p [手动隐藏] yqtb
Traceback (most recent call last):
  File "/home/kelvin/Desktop/AoxiangRobot/aoxiangRobot", line 147, in <module>
    parser.dispatch()
  File "/home/kelvin/.local/lib/python3.9/site-packages/argh/helpers.py", line 55, in dispatch
    return dispatch(self, *args, **kwargs)
  File "/home/kelvin/.local/lib/python3.9/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/home/kelvin/.local/lib/python3.9/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/home/kelvin/.local/lib/python3.9/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "/home/kelvin/Desktop/AoxiangRobot/aoxiangRobot", line 126, in yqtb
    res = Aoxiang(username, password).yqtb(location=kwargs['location'])
  File "/home/kelvin/.local/lib/python3.9/site-packages/QingQiz/netreq/aoxiang.py", line 533, in yqtb
    uid    = self.userInfo['basicInformation']['id']
  File "/home/kelvin/.local/lib/python3.9/site-packages/QingQiz/netreq/aoxiang.py", line 244, in userInfo
    res = self.fullUserInfo
  File "/home/kelvin/.local/lib/python3.9/site-packages/QingQiz/netreq/aoxiang.py", line 210, in fullUserInfo
    res = self.req(f'https://ecampus.nwpu.edu.cn/portal-web/api/rest/portalUser/selectUserInfoByCurrentUser', params={
  File "/usr/lib/python3.9/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib64/python3.9/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.9/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib64/python3.9/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

好像只有 me 和 yqtb 有问题，exam 和 grade 没有问题QAQ

先提个issue，说不定明天又找到解决方法了呢owo

**Comment by QingQiz** [comment]
这个问题我很早之前就发现了，原因是翱翔门户的认证似乎有点变化，直接登录拿不到API Key了，还没来得及修。

**Comment by QingQiz** [comment]
原因找到了，原来的 `x-id-token` 是在某个请求中给出来的，现在是通过一段混淆过的 js 算出来的，js 代码是：

```js
function l(e) {
    var t=new RegExp("(^|&)"+e+"=([^&]*)(&|$)","i");
    var n=window.location.search.substr(1).match(t);
    return null!=n?unescape(n[2]):null
}

var c=localStorage.getItem("token");

t.token=c;

c="eyJhbGciOiJSUzUxMiJ9.eyJzdWIiOiIyMDAxMDIwMDQ5IiwiaXNzIjoidWlzLnBhYXMubndwdS5lZHUuY24iLCJBVFRSX2lkZW50aXR5VHlwZUlkIjoiVDAxIiwiQVRUUl9hY2NvdW50SWQiOiIyMDAxMDIwMDQ5IiwiQVRUUl91c2VySWQiOiIyMDAxMDIwMDQ5IiwiQVRUUl9uYW1lIjoi6buE5pmT5rOiIiwiQVRUUl9pZGVudGl0eVR5cGVDb2RlIjoiVDAxIiwiQVRUUl9pZGVudGl0eVR5cGVOYW1lIjoi5pWZ6IGM5belIiwiQVRUUl9vcmdhbml6YXRpb25OYW1lIjoi5L-h5oGv5YyW5bu66K6-5LiO566h55CG5aSEIiwiQVRUUl91c2VyTmFtZSI6Ium7hOaZk-azoiIsImV4cCI6MTYyNTExNzk0OCwiQVRUUl9vcmdhbml6YXRpb25JZCI6IjAyMjYwIiwiaWF0IjoxNjIzOTA4MzQ4LCJqdGkiOiJJRC1Ub2tlbi0yODE0LTA1LTVhUmdvQkxaSGlzaUtOWDVJbklFa3ZEbGUzRXdHIiwicmVxIjoiYWRtaW4tY2VudGVyLnBhYXMubndwdS5lZHUuY24iLCJBVFRSX29yZ2FuaXphdGlvbkNvZGUiOiIwMjI2MCJ9.HWPjgtgDIQMMR3nYZ4RpcF9tJ_GTUnxlFauhrN2SGYpxaQYuSxZXuiLHiDbNthbCygt-GS7rIXrdHNU5jCu-Ltk3jyAHoMHD9btjCEPEyt0PX8EIDsIJemtY0QnDwAVlxOniTR_vjx_eHt9no1EHE0gaStPOu4x135lN25gqHpo";

t.token=c, c || (t.token=c=l("token"),window.localStorage.setItem("token",c))
```

可以用 python 模拟这段 js 代码解决

**Comment by QingQiz** [comment]
修好了，见 [`314c3df`](https://github.com/QingQiz/python_modules/commit/314c3df5ec6d6b2c83adcd22fc259febdb5ac9c5) 45ef8e600ac2480a05a73b5c34a48b02602f8452

执行 `pip install --upgrade -r requirements.txt` 获取更新
